// Responsive width variants generated by scripts/optimize-media.sh
const WIDTH_VARIANTS = [640, 1024, 1920];

// Build a srcSet from a base image path, e.g. "/images/pool-1.webp" →
// "/images/pool-1-640w.webp 640w, /images/pool-1-1024w.webp 1024w, ..."
export function srcSetFor(src: string): string {
  const base = src.replace(/\.webp$/, "");
  return WIDTH_VARIANTS.map((width) => `${base}-${width}w.webp ${width}w`).join(
    ", ",
  );
}
